
services:
  users-api-test:
    image: api:v1
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 2gb
    volumes:
      - ./:/usr/workspace
      - /dev/shm:/dev/shm
      - ./allure-results:/usr/workspace/allure-results


    command: /bin/sh -c "HOST_URL=$$HOST_URL pytest -sv -o log_cli=true -m=$$MARKER --alluredir=allure-results"
    environment:
      HOST_URL: ${HOST_URL}
      MARKER: ${MARKER:-auth}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_CHAT_ID: ${TG_CHAT_ID}
      GH_PAGES_URL: ${GH_PAGES_URL}
    tty: true

  report:
    image: api:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace



